routes/web.php
<?php

//use Illuminate\Support\Facades\App;
use App\User;

#use Symfony\Component\Routing\Route;
//use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('job',function(){
    dispatch(new App\Jobs\SendEmail);
    return "Listo!";
});

//Mostrar en pantalla las consultas SQL
DB::listen(function($query){
    //echo "<pre>{$query->sql}</pre>";
    //echo "<pre>{$query->time}</pre>";
});

Route::get('test',function(){
    $user = new User;
    $user->name = "Prueba";
    $user->email = "prueba@prueba.com";
    $user->password = bcrypt("Ejemplo123");
    $user->save();
    return $user;
});

Route::get('roles',function(){
    return \App\Role::with('user')->get();
});

//Route::get('/')->name('home')->uses('PagesController@home')->middleware('example');
Route::get('/')->name('home')->uses('PagesController@home');
Route::get('/contactame')->name('contactos')->uses('PagesController@contact');
Route::post('contacto','PagesController@mensajes');
Route::get('/saludos/{nombre?}')->name('saludos')->uses('PagesController@saludo')->where('nombre',"[A-Za-z]+");

//Se cambia todas las rutas del controlados a una sola linea
Route::resource('mensajes','MessagesController');
Route::resource('usuarios','UsersController');

/*Route::get('login','Auth\LoginController@showLoginForm');
Route::post('login','Auth\LoginController@login');*/

//Retornando vistas

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

/*Route::get('/mensajes')->name('messages.index')->uses('MessagesController@index');
Route::get('/mensajes/create')->name('messages.create')->uses('MessagesController@create');
Route::post('/mensajes')->name('messages.store')->uses('MessagesController@store');
Route::get('/mensajes/{id}')->name('messages.show')->uses('MessagesController@show');
Route::get('/mensajes/{id}/edit')->name('messages.edit')->uses('MessagesController@edit');
Route::put('/mensajes/{id}')->name('messages.update')->uses('MessagesController@update');
Route::delete('/mensajes/{id}')->name('messages.destroy')->uses('MessagesController@destroy');*/

//Pasar parametros por url
/*Route::get('/saludos/{nombre?}', function ($nombre = "Invitado") {
    //return "Saludos $nombre";
    //return view('saludo',['nombre' => $nombre]);
    //return view('saludo')->with(['nombre' => $nombre]);
    $html ="<h2>Contenido html</h2>";
    $script = "<script>alert('Problem XSS - Cross Site scripting!!!')</script>";

    $consolas = [
        'Play Station 4',
        'Xbox One',
        'Wii U',
        'Nintendo Switch'
    ];

    return view('saludo',compact('nombre','html','script','consolas'));
})->name('saludos');*/



//Parametros opcionales
/*Route::get('/saludos2/{nombre?}', function ($nombre = "Invitado") {
    return "Saludos $nombre";
});*/

//Validar un parametro
/*Route::get('/saludos3/{nombre?}', function ($nombre = "Invitado") {
    return "Saludos $nombre";
})->where('nombre',"[A-Za-z]+");*/


//Rutas con nombre
/*Route::get('/contacto', function () {
    //return "Esta es la seccion de contactos XD";
    return view('contactos');
})->name('contactos');*/

resources/views/home__.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="/css/app.css"/>
    <title>Mi sitio</title>
</head>
<body>
    <header>
        <!--h1>{{-- request()->url() --}}</h1-->

        <?php function activeMenu($url){
            return  request()->is($url) ? 'active' : '';
        }?>

        <nav class="navbar navbar-default" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Mi sitio</a>
                </div>
    
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav">
                        <li class="{{ activeMenu('/') }}">
                            <a href="{{ route('home') }}">Inicio</a>
                        </li>
                        <li class="{{ activeMenu('saludos/*') }}">
                            <a href="{{ route('saludos','Guillermo') }}">Saludos</a>
                        </li>
                        <li class="{{ activeMenu('mensajes/create') }}">
                            <a href="{{ route('mensajes.create') }}">Contactos</a>
                        </li>
                        @if(Auth()->check())
                        <li class="{{ activeMenu('mensajes*') }}">
                            <a href="{{ route('mensajes.index') }}">Mensajes</a>
                        </li>
                            @if(Auth()->user()->hasRoles(['admin']))
                            <li class="{{ activeMenu('mensajes*') }}">
                                <a href="{{ route('usuarios.index') }}">Usuarios</a>
                            </li>
                            @endif
                        @endif
                    </ul>
                    
                    <ul class="nav navbar-nav navbar-right">
                        @if(Auth()->guest())
                        <li class="{{ activeMenu('login') }}">
                            <a href="{{ route('login') }}">Login</a>
                        </li>
                        @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ Auth()->user()->name }} <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="/usuarios/{{ auth()->id() }}/edit">Mi cuenta</a>
                                </li>
                                <li class="{{ activeMenu('logout') }}">
                                    <a href="{{ route('logout') }}" 
                                        onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                        Cerrrar sesión
                                    </a>
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                        @endif
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div>
        </nav>

    </header>
    
    <div class="container">
        @yield('contenido')
        <br>
        <footer>Copyright &copy; {{ date('Y') }}</footer>
    </div>
    <script src="{{asset('js/jQuery/jquery-1.9.1.min.js')}}"></script>
    <script src="{{asset('js/bootstrap/bootstrap.min.js')}}"></script>
    <script src="{{asset('js/script.js')}}"></script>
</body>
</html>

resources/views/saludo.blade.php
@extends('layout')

@section('contenido')
    <h1>Saludos a {{ $nombre }}</h1>
@endsection