routes/web.php
<?php

//use Illuminate\Support\Facades\App;
use App\User;

#use Symfony\Component\Routing\Route;
//use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('job',function(){
    dispatch(new App\Jobs\SendEmail);
    return "Listo!";
});

//Mostrar en pantalla las consultas SQL
DB::listen(function($query){
    //echo "<pre>{$query->sql}</pre>";
    //echo "<pre>{$query->time}</pre>";
});

Route::get('test',function(){
    $user = new User;
    $user->name = "Prueba";
    $user->email = "prueba@prueba.com";
    $user->password = bcrypt("Ejemplo123");
    $user->save();
    return $user;
});

Route::get('roles',function(){
    return \App\Role::with('user')->get();
});

//Route::get('/')->name('home')->uses('PagesController@home')->middleware('example');
Route::get('/')->name('home')->uses('PagesController@home');
Route::get('/contactame')->name('contactos')->uses('PagesController@contact');
Route::post('contacto','PagesController@mensajes');
Route::get('/saludos/{nombre?}')->name('saludos')->uses('PagesController@saludo')->where('nombre',"[A-Za-z]+");

//Se cambia todas las rutas del controlados a una sola linea
Route::resource('mensajes','MessagesController');
Route::resource('usuarios','UsersController');

/*Route::get('login','Auth\LoginController@showLoginForm');
Route::post('login','Auth\LoginController@login');*/

//Retornando vistas

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

/*Route::get('/mensajes')->name('messages.index')->uses('MessagesController@index');
Route::get('/mensajes/create')->name('messages.create')->uses('MessagesController@create');
Route::post('/mensajes')->name('messages.store')->uses('MessagesController@store');
Route::get('/mensajes/{id}')->name('messages.show')->uses('MessagesController@show');
Route::get('/mensajes/{id}/edit')->name('messages.edit')->uses('MessagesController@edit');
Route::put('/mensajes/{id}')->name('messages.update')->uses('MessagesController@update');
Route::delete('/mensajes/{id}')->name('messages.destroy')->uses('MessagesController@destroy');*/

//Pasar parametros por url
/*Route::get('/saludos/{nombre?}', function ($nombre = "Invitado") {
    //return "Saludos $nombre";
    //return view('saludo',['nombre' => $nombre]);
    //return view('saludo')->with(['nombre' => $nombre]);
    $html ="<h2>Contenido html</h2>";
    $script = "<script>alert('Problem XSS - Cross Site scripting!!!')</script>";

    $consolas = [
        'Play Station 4',
        'Xbox One',
        'Wii U',
        'Nintendo Switch'
    ];

    return view('saludo',compact('nombre','html','script','consolas'));
})->name('saludos');*/



//Parametros opcionales
/*Route::get('/saludos2/{nombre?}', function ($nombre = "Invitado") {
    return "Saludos $nombre";
});*/

//Validar un parametro
/*Route::get('/saludos3/{nombre?}', function ($nombre = "Invitado") {
    return "Saludos $nombre";
})->where('nombre',"[A-Za-z]+");*/


//Rutas con nombre
/*Route::get('/contacto', function () {
    //return "Esta es la seccion de contactos XD";
    return view('contactos');
})->name('contactos');*/

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Presenters\UserPresenter;
use Illuminate\Database\Eloquent\Model;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    //La nomenclatura para el nombre de estos metodos es set, para indicar que se va a modificar el valor antes de guardarlo
    //El segundo vaor el el nombre del campo, en esta caso password y por ultimo la palabra attribute
    public function setPasswordAttribute($password) {
        $this->attributes['password'] = bcrypt($password);
    }    

    //Metodo para establecer la realacion con la tabla roles
    public function roles() {
        return $this->belongsToMany(Role::class,'assigned_roles');
    }

    //Metodo para verificar que roles tiene el usuario
    public function hasRoles(array $roles) {
        return $this->roles->pluck('name')->intersect($roles)->count();
        /*foreach($roles as $role){
            foreach($this->roles as $userRole){
                if($userRole->name === $role){
                    return true;
                }
            }
        }
        return false;*/
    }

    //Metodo para saber si el usuario es admin
    public function isAdmin(){
        return $this->hasRoles(['admin']);
    }

    //Metodo para establecer la relacion con la tabla messages
    public function messages(){
        return $this->hasMany(Message::class);
    }

    //Agregar notas al usuario
    public function note(){
        return $this->morphOne(Note::class,'notable');
    }

    public function tags() {
        return $this->morphToMany(Tag::class, 'taggable')->withTimestamps();
    }

    public function present(){
        return new UserPresenter($this);
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Role;
use Illuminate\Http\Request;
use App\Http\Requests\RegisterUserRequest;
use App\Http\Requests\UpadateUserRequest;

class UsersController extends Controller
{
    public function __construct()
    {
        /*$this->middleware(
            [
                'auth',
                'roles:admin'
            ]
        );*/
        $this->middleware('auth',['except' => ['show']]);
        $this->middleware('roles:admin',['except' => ['edit','update','show']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //$users = \App\User::all();
        $users = User::with(['roles','note','tags'])->get();
        return view('users.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::pluck('display_name','id');
        return view('users.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\RegisterUserRequest
     * @return \Illuminate\Http\Response
     */
    public function store(RegisterUserRequest $request)
    {
        //Se crea el nuevo usuario
        $user = User::create($request->all());
        //Se le asignan los roles
        $user->roles()->attach($request->roles);
        //Se redirige a la ventana index
        return redirect()->route('usuarios.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::findOrFail($id);
        return view('users.show',compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);

        //Se verifica si esta autrizado para editar
        $this->authorize('edit',$user);

        $roles = Role::pluck('display_name','id');

        return view('users.edit',compact('user','roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpadateUserRequest $request, $id)
    {
        $user = User::findOrFail($id);
        //Se verifica si esta autorizado para el metodo update
        $this->authorize('update',$user);

        //Que solo actualice nombre y correo
        $user->update($request->only('name','email'));
        //Asignacion de los roles recibidos por formulario
        #$user->roles()->attach($request->roles);
        //Para evitar que cada que se realice el atach los roles se supliquen se usa el metodo sync
        $user->roles()->sync($request->roles);

        return back()->with('info','Usuario actualizado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        //Se verifica si esta autorizado para el metodo destroy
        $this->authorize('destroy',$user);
        
        $user->delete();
        return back();
    }
}

resources/views/users/create.blade.php
@extends('layout')

@section('contenido')
    <h1>Crear usuario</h1>

    <form action="{{ route('usuarios.store') }}" method="POST">

        @include('users.form',['user' => new App\User])
  
        <input type="submit" class="btn btn-primary" value="Guardar">
    </form>
@endsection

resources/views/users/edit.blade.php
@extends('layout')

@section('contenido')
    <h1>Editar Usuario</h1>

    @if(session()->has('info'))
        <div class="alert alert-success">
            {{ session('info') }}
        </div>
    @endif

    <form action="{{ route('usuarios.update',$user->id) }}" method="POST">
        {!! method_field('PUT') !!}
        {!! csrf_field() !!}
        <p>
            <label for="nombre">
                Nombre
                <input type="text" class="form-control" name="name" value="{{ $user->name }}">
                {!! $errors->first('name','<span class=error>:message</span>') !!}
            </label>
        </p>

        <p>
            <label for="email">
                Email
                <input type="email" name="email" class="form-control" value="{{ $user->email }}">
                {!! $errors->first('email','<span class=error>:message</span>') !!}
            </label>
        </p>

        <div class="checkbox">
            @foreach ($roles as $id => $name)
                <label>
                    <input type="checkbox" name="roles[]" value="{{ $id }}" {{ $user->roles->pluck('id')->contains($id) ? 'checked' : '' }}>
                    {{ $name }}
                </label>
            @endforeach
        </div>

        <input type="submit" class="btn btn-primary" value="Enviar">
    </form>
@endsection

resources/views/users/form.blade.php
{!! csrf_field() !!}
<p>
    <label for="nombre">
        Nombre
        <input type="text" class="form-control" name="name" value="{{ $user->name or old('name') }}">
        {!! $errors->first('name','<span class=error>:message</span>') !!}
    </label>
</p>

<p>
    <label for="email">
        Email
        <input type="email" name="email" class="form-control" value="{{ $user->email or old('email') }}">
        {!! $errors->first('email','<span class=error>:message</span>') !!}
    </label>
</p>

@unless ($user->id)
<p>
    <label for="password">
        Password
        <input type="password" class="form-control" name="password">
        {!! $errors->first('password','<span class=error>:message</span>') !!}
    </label>
</p>

<p>
    <label for="password_confirmation">
        Password Confirm
        <input type="password" class="form-control" name="password_confirmation">
        {!! $errors->first('password_confirmation','<span class=error>:message</span>') !!}
    </label>
</p>
        
@endunless

<div class="checkbox">
    @foreach ($roles as $id => $name)
        <label>
            <input type="checkbox" name="roles[]" value="{{ $id }}" {{ $user->roles->pluck('id')->contains($id) ? 'checked' : '' }}>
            {{ $name }}
        </label>
    @endforeach
</div>
{!! $errors->first('roles','<span class=error>:message</span>') !!}
<br>

resources/views/users/index.blade.php
@extends('layout')

@section('contenido')
    <h1>Usuarios</h1>    
    <a href="{{ route('usuarios.create') }}" class="btn btn-primary pull-right">Crear nuevo usuario</a>
    <table class="table">
            <head>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Email</th>
                    <th>Role</th>
                    <th>Notas</th>
                    <th>Etiquetas</th>
                    <th>Acciones</th>
                </tr>
            </head>
            <tbody>
                @foreach ($users as $user)
                    <tr>
                        <td>{{ $user->id }}</td>
                        <td>{{ $user->present()->link() }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->present()->roles() }}</td>
                        <td>{{ $user->present()->notes() }}</td>
                        <td>{{ $user->present()->tags() }}</td>
                        <td>
                            <a href="{{ route("usuarios.edit",$user->id) }}" class="btn btn-info btn-xs">Editar</a>
                            <form style="display:inline;" action="{{ route("usuarios.destroy",$user->id) }}" method="POST">
                                {!! csrf_field() !!}
                                {!! method_field('DELETE') !!}
                                <button type="submit" class="btn btn-danger btn-xs">Eliminar</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
@endsection

resources/views/users/show.blade.php
@extends('layout')

@section('contenido')
    <h1>{{ $user->name }}</h1>

    <table class="table">
        <tr>
            <th>Nombre: </th>
            <td>{{ $user->name }}</td>
        </tr>
        <tr>
            <th>Email: </th>
            <td>{{ $user->email }}</td>
        </tr>
        <tr>
            <th>Roles: </th>
            <td>
                @foreach ( $user->roles as $role )
                    {{ $role->display_name }}
                @endforeach
            </td>
        </tr>
    </table>

    @can('edit', $user)
        <a href="{{ route('usuarios.edit',$user->id) }}" class="btn btn-info">Editar</a>        
    @endcan

    @can('destroy', $user)
        <form style="display:inline;" action="{{ route("usuarios.destroy",$user->id) }}" method="POST">
            {!! csrf_field() !!}
            {!! method_field('DELETE') !!}
            <button type="submit" class="btn btn-danger">Eliminar</button>
        </form>
    @endcan

@endsection