routes/web.php
<?php

//use Illuminate\Support\Facades\App;
use App\User;

#use Symfony\Component\Routing\Route;
//use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('job',function(){
    dispatch(new App\Jobs\SendEmail);
    return "Listo!";
});

//Mostrar en pantalla las consultas SQL
DB::listen(function($query){
    //echo "<pre>{$query->sql}</pre>";
    //echo "<pre>{$query->time}</pre>";
});

Route::get('test',function(){
    $user = new User;
    $user->name = "Prueba";
    $user->email = "prueba@prueba.com";
    $user->password = bcrypt("Ejemplo123");
    $user->save();
    return $user;
});

Route::get('roles',function(){
    return \App\Role::with('user')->get();
});

//Route::get('/')->name('home')->uses('PagesController@home')->middleware('example');
Route::get('/')->name('home')->uses('PagesController@home');
Route::get('/contactame')->name('contactos')->uses('PagesController@contact');
Route::post('contacto','PagesController@mensajes');
Route::get('/saludos/{nombre?}')->name('saludos')->uses('PagesController@saludo')->where('nombre',"[A-Za-z]+");

//Se cambia todas las rutas del controlados a una sola linea
Route::resource('mensajes','MessagesController');
Route::resource('usuarios','UsersController');

/*Route::get('login','Auth\LoginController@showLoginForm');
Route::post('login','Auth\LoginController@login');*/

//Retornando vistas

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

/*Route::get('/mensajes')->name('messages.index')->uses('MessagesController@index');
Route::get('/mensajes/create')->name('messages.create')->uses('MessagesController@create');
Route::post('/mensajes')->name('messages.store')->uses('MessagesController@store');
Route::get('/mensajes/{id}')->name('messages.show')->uses('MessagesController@show');
Route::get('/mensajes/{id}/edit')->name('messages.edit')->uses('MessagesController@edit');
Route::put('/mensajes/{id}')->name('messages.update')->uses('MessagesController@update');
Route::delete('/mensajes/{id}')->name('messages.destroy')->uses('MessagesController@destroy');*/

//Pasar parametros por url
/*Route::get('/saludos/{nombre?}', function ($nombre = "Invitado") {
    //return "Saludos $nombre";
    //return view('saludo',['nombre' => $nombre]);
    //return view('saludo')->with(['nombre' => $nombre]);
    $html ="<h2>Contenido html</h2>";
    $script = "<script>alert('Problem XSS - Cross Site scripting!!!')</script>";

    $consolas = [
        'Play Station 4',
        'Xbox One',
        'Wii U',
        'Nintendo Switch'
    ];

    return view('saludo',compact('nombre','html','script','consolas'));
})->name('saludos');*/



//Parametros opcionales
/*Route::get('/saludos2/{nombre?}', function ($nombre = "Invitado") {
    return "Saludos $nombre";
});*/

//Validar un parametro
/*Route::get('/saludos3/{nombre?}', function ($nombre = "Invitado") {
    return "Saludos $nombre";
})->where('nombre',"[A-Za-z]+");*/


//Rutas con nombre
/*Route::get('/contacto', function () {
    //return "Esta es la seccion de contactos XD";
    return view('contactos');
})->name('contactos');*/

app/Message.php
<?php

namespace App;

use App\Presenters\MessagePresenter;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User;

class Message extends Model
{
    protected $fillable = ['nombre','email','mensaje'];

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function note(){
        return $this->morphOne(Note::class,'notable');
    }

    public function tags() {
        return $this->morphToMany(Tag::class, 'taggable');
    }

    public function present(){
        return new MessagePresenter($this);
    }
}

app/Http/Controllers/MessagesController.php
<?php

namespace App\Http\Controllers;

use DB;
use Mail;
use Carbon\Carbon;
use App\Message;
use Illuminate\Http\Request;
use App\Http\Requests\CreateMessageRequest;
use App\Events\MessageWasReceived;
use Illuminate\Support\Facades\Cache;
use App\Repositories\Messages;
//use App\Repositories\CacheMessages;
use App\Repositories\MessagesInterface;

class MessagesController extends Controller
{
    protected $messages;

    //public function __construct(CacheMessages $messages){
        public function __construct(Messages $messages){
        $this->messages = $messages;
        $this->middleware('auth',['except' => ['create','store']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //$key = "messages.page.".request("page",1);
        //Taer todos los registros de la tabla
        //Query Builder
        #$messages = DB::table('messages')->get();
        //Eloquent
        //$messages = Message::all();
        //$messages = Cache::remember($key,5,function(){
        /*$messages = Cache::tags('messages')->rememberForever($key,function(){
            //Para paginar los resultados se cambia el metodo get por paginate
            return Message::with(['user','note','tags'])
                        ->orderBy('created_at',request('sorted','DESC'))
                        ->paginate(10);
        });*/
        /*if(Cache::has($key)){
            $messages = Cache::get($key);    
        }else{
            //Para paginar los resultados se cambia el metodo get por paginate
            $messages = Message::with(['user','note','tags'])
                        ->orderBy('created_at',request('sorted','ASC'))
                        ->paginate(10);
            Cache::put($key,$messages,5);
        }*/
        $messages = $this->messages->getPaginated();
        return view('messages.index',compact('messages'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('messages.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateMessageRequest $request)
    {
        //Guardar mensaje
        //Query builder
        /*DB::table('messages')->insert([
            "nombre" => $request->input('nombre'),
            "email" => $request->input('email'),
            "mensaje" => $request->input('mensaje'),
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);*/
        //Eloquent
        //--Forma 1
        /*$message = new Message();
        $message->nombre = $request->input('nombre');
        $message->email = $request->input('email');
        $message->mensaje = $request->input('mensaje');
        $message->save();*/
        //--Forma 2
        /*Message::create([
            "nombre" => $request->input('nombre'),
            "email" => $request->input('email'),
            "mensaje" => $request->input('mensaje'),
        ]);*/
        //--Forma 3
        #$message = Message::create($request->all());
        
        /*if(auth()->check()){
            auth()->user()->messages()->save($message);
        }*/

        //Limpiar la cache
        #Cache::tags('messages')->flush();
        
        //El metodo send del obtejo Mail recive 3 parametros
        //1.- La vista
        //2.- Parametros para la vista
        //3.- Una funcion anonima con el parametro message
        /*Mail::send('emails.contact',['msg' => $message],function($msg) use ($message){
            $msg->to($message->email,$message->name)->subject('Tu mensaje fue recibido');
        });*/
        $message = $this->messages->store($request);
        //Ahora el envio del correo se realiza mediante un evento
        event(new MessageWasReceived($message));

        //Esta forma sirve cuando savemos que siempre tenemos un usuario autenticado
        //auth()->user()->messages()->create($request->all());
        
        return redirect()->route('mensajes.create')->with('info','Hemos recibido tu mensaje');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        /*$message = Cache::tags('messages')->rememberForever("message.{$id}",function() use ($id){
            //Eloquent 
            return Message::findOrFail($id);
        });*/
        //Obtener un mensaje
        //Query Builder
        #$message = DB::table("messages")->where("id",$id)->first();
        //Eloquent 
        //$message = Message::findOrFail($id);
        $message = $this->messages->findById($id);
        return view('messages.show',compact('message'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //Obtener mensaje
        //Query Builder
        #$message = DB::table("messages")->where("id",$id)->first();
        /*$message = Cache::tags('messages')->rememberForever("message.{$id}",function() use ($id){
            //Eloquent 
            return Message::findOrFail($id);
        });*/
        //Eloquent
        //$message = Message::findOrFail($id);
        $message = $this->messages->findById($id);
        return view("messages.edit",compact("message"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //Actualizar mensaje
        //Query Builder
        /*DB::table('messages')->where('id',$id)->update([
            "nombre" => $request->input('nombre'),
            "email" => $request->input('email'),
            "mensaje" => $request->input('mensaje'),
            "updated_at" => Carbon::now()
        ]);*/
        //Eloquent
        #$message = Message::findOrFail($id);
        #$message->update($request->all());
        #Cache::tags('messages')->flush();
        $this->messages->update($request,$id);
        return redirect()->route('mensajes.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //Eliminar Mensaje
        //Query Builder
        #DB::table('messages')->where('id',$id)->delete();
        //Eloquent
        /*$message = Message::findOrFail($id);
        $message->delete();
        Cache::tags('messages')->flush();*/
        $this->messages->destroy($id);
        //Redirecconar
        return redirect()->route('mensajes.index');
    }
}

resources/views/messages/create.blade.php
@extends('layout')

@section('contenido')
    <h1>Contactos</h1>
    <h2>Escribeme</h2>
    @if (session()->has('info'))
        {{ session('info') }}
    @else
    <form action="{{ route('mensajes.store') }}" method="POST">
        @include('messages.form',[
            'message' => new App\Message,
            'showFields' => auth()->guest()
        ])
    </form>
    @endif
@endsection

resources/views/messages/edit.blade.php
@extends('layout')

@section('contenido')
    <h1>Editar mensaje de {{ $message->nombre }}</h1>
    <form action="{{ route('mensajes.update',$message->id) }}" method="POST">
        {!! method_field('PUT') !!}
        @include('messages.form',[
            'btnText' => 'Actualizar',
            'showFields' => !$message->user_id
        ])
    </form>
@endsection

resources/views/messages/form.blade.php
{!! csrf_field() !!}

@if ($showFields)
    
    <p>
        <label for="nombre">
            Nombre
            <input class="form-control" type="text" name="nombre" value="{{ $message->nombre or old('nombre') }}">
            {!! $errors->first('nombre','<span class=error>:message</span>') !!}
        </label>
    </p>

    <p>
        <label for="email">
            Email
            <input type="email" class="form-control" name="email" value="{{ $message->email or old('email') }}">
            {!! $errors->first('email','<span class=error>:message</span>') !!}
        </label>
    </p>
@endif

<p>
    <label for="mensaje">
        Mensaje
        <textarea name="mensaje" class="form-control" cols="30" rows="10">{{ $message->mensaje or old('mensaje') }}</textarea>
        {!! $errors->first('mensaje','<span class=error>:message</span>') !!}
    </label>
</p>

<input type="submit" class="btn btn-primary" value="{{ isset($btnText) ? $btnText :'Guardar' }}">

resources/views/messages/home.blade.php
@extends('layout')

@section('contenido')
<h1>Home</h1>    
@endsection

resources/views/messages/index.blade.php
@extends('layout')

@section('contenido')
    <h1>Todos los mensajes</h1>

    <table class="table">
        <head>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Email</th>
                <th>Mensaje</th>
                <th>Notas</th>
                <th>Etiquetas</th>
                <th>Acciones</th>
            </tr>
        </head>
        <tbody>
            @foreach ($messages as $message)
                <tr>
                    <td>{{ $message->id }}</td>
                    <td>{{ $message->present()->userName()  }}</td>
                    <td>{{ $message->present()->userEmail() }}</td>
                    <td>{{ $message->present()->link() }}</td>
                    <td>{{ $message->present()->notes() }}</td>
                    <td>{{ $message->present()->tags() }}</td>
                    <td>
                        <a href="{{ route("mensajes.edit",$message->id) }}" class="btn btn-info btn-xs">Editar</a>
                        <form style="display:inline;" action="{{ route("mensajes.destroy",$message->id) }}" method="POST">
                            {!! csrf_field() !!}
                            {!! method_field('DELETE') !!}
                            <button type="submit" class="btn btn-danger btn-xs">Eliminar</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            {{-- $messages->appends(request()->query())->links('pagination.custom') --}}
            {{ $messages->fragment('hash')->appends(request()->query())->links('pagination::default') }}
        </tbody>
    </table>
@endsection

resources/views/messages/show.blade.php
@extends('layout')

@section('contenido')
    <h1>Mensaje</h1>

    <p>Enviado por {!! $message->present()->userName() !!} - {{ $message->present()->userEmail() }}</p>
    <p>{{ $message->mensaje }}</p>
@endsection